# Generated by Django 5.1.4 on 2025-01-09 19:47

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpenseapp', '0002_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='completed',
            new_name='complete',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='target_date',
            new_name='timeline',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='current_progress',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='goal_name',
        ),
        migrations.AddField(
            model_name='goal',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='progress',
            field=models.PositiveIntegerField(default=datetime.date(2025, 1, 9)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='priority',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
